# Generated by Django 5.2.4 on 2025-07-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='description',
        ),
        migrations.AddField(
            model_name='table',
            name='announcement',
            field=models.TextField(blank=True, help_text='Optional. This message will be shown at the top of the table for all members.'),
        ),
    ]
