# Generated by Django 5.2.4 on 2025-07-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_groups', '0002_remove_table_description_table_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='admin_color',
            field=models.CharField(default='#3949ab', max_length=7),
        ),
        migrations.AddField(
            model_name='table',
            name='member_color',
            field=models.CharField(default='#43a047', max_length=7),
        ),
        migrations.AddField(
            model_name='table',
            name='owner_color',
            field=models.CharField(default='#e53935', max_length=7),
        ),
    ]
