# Generated by Django 5.2.4 on 2025-07-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='location_type',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('in_person', 'In Person')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ad',
            name='session_frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('one_shot', 'One-shot'), ('infrequent', 'Infrequent')], max_length=20),
        ),
    ]
