# Generated by Django 5.2.4 on 2025-07-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_location_type_alter_ad_session_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='location_type',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('In Person', 'In Person')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ad',
            name='session_frequency',
            field=models.CharField(blank=True, choices=[('Weekly', 'Weekly'), ('Biweekly', 'Biweekly'), ('Monthly', 'Monthly'), ('One shot', 'One-shot'), ('Infrequent', 'Infrequent')], max_length=20),
        ),
    ]
