# Generated by Django 5.2.4 on 2025-07-30 04:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(help_text='You must be at least 18 years old to register.', validators=[django.core.validators.MinValueValidator(18, message='You must be at least 18 years old to register.')]),
        ),
    ]
