# Generated by Django 5.2.4 on 2025-07-14 21:05

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(default=18, help_text='You must be at least 18 years old to register.', max_length=3, validators=[django.core.validators.MinValueValidator(18, message='You must be at least 18 years old to register.')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 4-30 characters long. Must start with a letter and contain only letters, numbers and underscores.', max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(4, message='Username must be at least 4 characters long'), accounts.validators.UsernameAlphaNumericUnderscoreValidator]),
        ),
    ]
