# Generated by Django 5.2.4 on 2025-07-14 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profile_age_customuser_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(default=18, help_text='You must be at least 18 years old to register.', validators=[django.core.validators.MinValueValidator(18, message='You must be at least 18 years old to register.')]),
        ),
    ]
