# Generated by Django 5.2.4 on 2025-07-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_names',
            field=models.BooleanField(default=True, help_text='Show your first and last name on your profile.'),
        ),
    ]
