# Generated by Django 5.2.4 on 2025-07-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_applications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='role',
            field=models.CharField(choices=[('dm', 'Dungeon Master'), ('player', 'Player'), ('both', 'Both')], max_length=10),
        ),
    ]
