# Generated by Django 5.2.4 on 2025-07-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='receiver',
            new_name='recipient',
        ),
    ]
